dist: bionic
language: php
php: 7.4
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install
script:
  - sh run-php-server.sh
  - sleep 2
  - php vendor/bin/codecept run --coverage --coverage-xml --steps
after_success:
  - bash <(curl -s https://codecov.io/bash)
