dist: bionic
language: php
php: 7.4
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - cp ./.ci/unit.suite.yml ./tests/unit.suite.yml
  - composer install
script:
  - php vendor/bin/codecept run --coverage --coverage-xml --steps
after_success:
  - bash <(curl -s https://codecov.io/bash)
