version: "3.1"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ritsema-banck
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "8181:80"

  openldap:
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=ritsema-banck
      - LDAP_DOMAIN=ritsema-banck.frl
      - LDAP_BASE_DN=dc=ritsema-banck,dc=frl
    volumes:
      - "./tmp/openldap:/var/lib/ldap"
      - "./tmp/openldap-config:/etc/ldap/slapd.d"
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8182:443"

  webserver:
    build: ./dev/
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/
    ports:
      - "8080:80"
