version: "3.1"
services:
  mariadb:
    container_name: RB_mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ritsema-banck
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./tmp/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: RB_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8181:80"

  openldap:
    container_name: RB_openldap
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=ritsema-banck
      - LDAP_DOMAIN=ritsema-banck.frl
      - LDAP_BASE_DN=dc=ritsema-banck,dc=frl
    volumes:
      - "./tmp/openldap:/var/lib/ldap"
      - "./tmp/openldap-config:/etc/ldap/slapd.d"
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    container_name: RB_phpldapadmin
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8182:443"

  webserver:
    container_name: RB_webserver
    build: ./dev/
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/
    ports:
      - "80:80"
