version: "3.1"
services:

  mysql:
    container_name: RB_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ritsema_banck
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"   

  phpmyadmin:
    container_name: RB_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "8181:80"

  openldap:
    container_name: RB_openldap
    image: osixia/openldap
    hostname: openldap
    environment:
      - LDAP_ORGANISATION=ritsema-banck
      - LDAP_DOMAIN=ritsema-banck.frl
      - LDAP_BASE_DN=dc=ritsema-banck,dc=frl
      - LDAP_TLS_VERIFY_CLIENT=try
    volumes:
      - "./tmp/openldap:/var/lib/ldap"
      - "./tmp/openldap-config:/etc/ldap/slapd.d"
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    container_name: RB_phpldapadmin
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8182:443"

  webserver:
    container_name: RB_webserver
    build: ./dev/web/
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    ports:
      - "80:80"
